config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  namespace :reader do
    # root 'dashboard#index'
    resources :books
    resources :categories
    resources :dashboard
    resources :issues 
    get 'issues/return/:id' => "issues#return"

  end
  
  namespace :admin do
    # root 'dashboard#index'
    resources :books
    resources :categories
    resources :dashboard
    resources :issues
    get 'issues/approve/:id' => "issues#approve"
  end

  root 'home#index'

  devise_for :users, controllers: { sessions: 'users/sessions' }
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :category
	extend FriendlyId
  	friendly_id :title, use: :slugged
	
	has_many :issues
	has_many :users,through: :issues

	validates :title, presence: true, length: { minimum: 5 }
	validates :author, presence: true, length: { minimum: 5 }

end

app/models/category.rb
class Category < ApplicationRecord
	has_many :books, dependent: :destroy
	validates :name, presence: true,length: { minimum: 5 }

end

app/models/issue.rb
class Issue < ApplicationRecord
	belongs_to :book
	belongs_to :user

	enum status: %i[notapproved approved returned]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   enum role: %i[reader admin]

   has_many :issues
   has_many :books,through: :users

   has_one_attached :avatar, :dependent => :destroy

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ActionController::Base
	layout 'admin'
	before_action :authenticate_user!
	before_action :check_reader

	private
		def check_reader
			user = current_user
			if user.reader?
				redirect_to reader_dashboard_index_path
			end
		end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::BaseController
  def index
    @books = Book.all
  end

  def show
  end

  def new
    @categories = Category.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
      if @book.save
        redirect_to admin_books_path
      else
        @categories = Category.all
        render :new
      end
  end

  def edit
    @book = Book.friendly.find(params[:id])
    @categories = Category.all
  end

  def update
    @book = Book.friendly.find(params[:id])
    @book.update(book_params)
    if @book.save
      redirect_to admin_books_path
    else
      render :edit
    end
  end

  def destroy
    @book = Book.friendly.find(params[:id])
    if @book.destroy
      redirect_to admin_books_path
    end
  end

  private
    def book_params
      params.require(:book).permit(:title, :author, :category_id)
    end
end

app/controllers/admin/issues_controller.rb
class Admin::IssuesController < Admin::BaseController
  def index
  	@issues = Issue.all
  end

  def approve
  	@issue = Issue.find(params[:id])
  	@issue.status = 1
  	if @issue.save
  		redirect_to admin_issues_path
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
before_action :check_roles

	def index; end

	private
		def check_roles
			if(user_signed_in?)	
				user = current_user
				if user.admin?
					redirect_to admin_dashboard_index_path
				elsif user.reader?
					redirect_to reader_dashboard_index_path
				end
			end
		end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/reader/base_controller.rb
class Reader::BaseController < ActionController::Base
	layout 'reader'
	before_action :authenticate_user!
	before_action :check_admin

	private
		def check_admin
			user = current_user
			if user.admin?
				redirect_to admin_dashboard_index_path
			end
		end
end

app/controllers/reader/books_controller.rb
class Reader::BooksController < Reader::BaseController
	# before_action :authenticate_user!

	def index
		if params[:search].present?
			@books = Book.search(params[:search]).records.all
		else
			@books = Book.all
		end
	end
end

app/controllers/reader/issues_controller.rb
class Reader::IssuesController < Reader::BaseController

	def index
		@issues = Issue.where(user_id: current_user.id)
	end

	def new
		@issue = Issue.new
		@books = Book.all
	end

	def create
		@issue = Issue.new(issues_params)
		@issue.user_id = current_user.id
		if @issue.save
			redirect_to reader_issues_path
		else
			render :new
		end 
	end

	def return
		@issue = Issue.find(params[:id])
		@issue.status = 2
		@issue.save
		redirect_to reader_issues_path
	end

	private
	def issues_params
      params.require(:issue).permit(:issue_date,:return_date,:book_id)
    end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/issue_helper.rb
module Admin::IssueHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_categories_helper.rb
module BookCategoriesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reader/base_helper.rb
module Reader::BaseHelper
end

app/helpers/reader/books_helper.rb
module Reader::BooksHelper
end

app/helpers/reader/categories_helper.rb
module Reader::CategoriesHelper
end

app/helpers/reader/dashboard_helper.rb
module Reader::DashboardHelper
end

app/helpers/reader/issue_helper.rb
module Reader::IssueHelper
end

app/views/admin/books/_form.html.erb
<div class="container">
<%= form_for [:admin,book] do |form| %>
  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title,class:'form-control' %>
  </div>
  <% book.errors.full_messages_for(:title).each do |message| %>
    <div class="text-danger"><%= message %></div>
  <% end %>

  <div class="form-group">
    <%= form.label :author %><br>
    <%= form.text_field :author,class:'form-control' %>
  </div>
  <% book.errors.full_messages_for(:author).each do |message| %>
    <div class="text-danger"><%= message %></div>
  <% end %>

  <div class="form-group">
  	<%= form.select :category_id,@categories.map{ |c| [c.name,c.id]},{},{:class=>'form-control'}%>
  </div>

   <div>
    <%= form.submit class:'btn btn-outline-secondary' %>
  </div>
<% end %>
</div>

app/views/admin/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/admin/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/admin/books/edit.html.erb
<h1 class="jumbotron">Edit Book</h1>

<%= render 'form', book:@book %>

app/views/admin/books/index.html.erb
<div class="jumbotron">
	<h1 class="display-4">View Books</h1>
	<h2 class="display-6"><%#= @category.name %></h2>
	

</div>

<div class="container">
	<table class="table table-striped">
		<thead>
			<th>id</th>
			<th>Book Title</th>
			<th>Book Author</th>
			<th>Category</th>
			<th>Action</th>
		</thead>
		<tbody>
			<% @books.each do |book| %> 
			<tr>
				<td><%= book.id%></td>
				<td><%= book.title %></td>
				<td><%= book.author %></td>
				<td><%= book.category.name %></td>
				<td><%= link_to 'Edit',edit_admin_book_path(book), class: 'btn btn-warning' %>
					<%= link_to 'Delete',admin_book_path(book), class: 'btn btn-danger', method: :delete,data: { confirm: "Are you sure?" } %>
				</td>
			</tr>
			<% end%>
		</tbody>
		
	</table>

	<%= link_to 'Add Book',new_admin_book_path, class:'btn btn-primary' %>
</div>

app/views/admin/books/new.html.erb
<h1 class="jumbotron">Add Book</h1>

<%= render "form",book: @book %>

app/views/admin/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/admin/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/admin/issues/index.html.erb
<div class="jumbotron">
	<h1 class="display-4">Admin View Issue Requests</h1>
	<p>All Book issue Requests</p>
	<%= link_to 'logout', destroy_user_session_path, method: :delete %>
</div>

<div class="container">
	<table class="table table-striped">
		<thead>
			<th>id</th>
			<th>Username</th>
			<th>Book Title</th>
			<th>Issue Date</th>
			<th>Return Date</th>
			<th>Status</th>
			<th>Action</th>
		</thead>
		<tbody>
			<% @issues.each do |issue| %> 
			<tr>
				<td><%= issue.id %></td>
				<td><%= issue.user.email %></td>
				<td><%= issue.book.title %></td>
				<td><%= issue.issue_date %></td>
				<td><%= issue.return_date %></td>
				<td><%= issue.status == 'approved' ? 'Approved' : issue.status == 'returned' ? 'Returned' : 'Not Approved'%></td>
				<td><%= link_to 'Approve',admin_path(issue.id), class: "btn btn-success btn-sm #{issue.status == 'returned' ? 'disabled' : issue.status == 'approved' ? 'disabled' : '' }", data: { confirm: "Are you sure?" } %>
				</td>
			</tr>
			<% end%>
		</tbody>
		
	</table>
</div>

app/views/admin/issues/new.html.erb
<div class="container">
<%= form_for [:admin,@request] do |form| %>
  <div class="form-group">
    <%= form.label :issue_date %><br>
    <%= form.date_select :issue_date %>
  </div>
  <% @request.errors.full_messages_for(:issue_date).each do |message| %>
    <div class="text-danger"><%= message %></div>
  <% end %>

  <div class="form-group">
    <%= form.label :issue_date %><br>
    <%= form.date_select :issue_date %>
  </div>
  </div>
  <% @requesy.errors.full_messages_for(:return_date).each do |message| %>
    <div class="text-danger"><%= message %></div>
  <% end %>

  <div class="form-group">
    <%= form.select :book_id,@books.map{ |c| [c.title,c.id]},{},{:class=>'form-control'}%>
  </div>

   <div>
    <%= form.submit class:'btn btn-outline-secondary' %>
  </div>
<% end %>
</div>