config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  namespace :reader do
    # root 'dashboard#index'
    resources :books
    resources :categories
    resources :dashboard
    resources :issues 
    get 'issues/return/:id' => "issues#return"

  end
  
  namespace :admin do
    # root 'dashboard#index'
    resources :books
    resources :categories
    resources :dashboard
    resources :issues
    get 'issues/approve/:id' => "issues#approve"
  end

  root 'home#index'

  devise_for :users, controllers: { sessions: 'users/sessions' }
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index
  end
end

app/controllers/reader/base_controller.rb
class Reader::BaseController < ActionController::Base
	layout 'reader'
	before_action :authenticate_user!
	before_action :check_admin

	private
		def check_admin
			user = current_user
			if user.admin?
				redirect_to admin_dashboard_index_path
			end
		end
end

app/controllers/reader/books_controller.rb
class Reader::BooksController < Reader::BaseController
	# before_action :authenticate_user!

	def index
		if params[:search].present?
			@books = Book.search(params[:search]).records.all
		else
			@books = Book.all
		end
	end
end

app/controllers/reader/categories_controller.rb
class Reader::CategoriesController < Reader::BaseController
	def index
		@categories = Category.all
	end
end

app/controllers/reader/dashboard_controller.rb
class Reader::DashboardController < Reader::BaseController
  def index
  end
end

app/controllers/reader/issues_controller.rb
class Reader::IssuesController < Reader::BaseController

	def index
		@issues = Issue.where(user_id: current_user.id)
	end

	def new
		@issue = Issue.new
		@books = Book.all
	end

	def create
		@issue = Issue.new(issues_params)
		@issue.user_id = current_user.id
		if @issue.save
			redirect_to reader_issues_path
		else
			render :new
		end 
	end

	def return
		@issue = Issue.find(params[:id])
		@issue.status = 2
		@issue.save
		redirect_to reader_issues_path
	end

	private
	def issues_params
      params.require(:issue).permit(:issue_date,:return_date,:book_id)
    end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/reader/base_helper.rb
module Reader::BaseHelper
end

app/helpers/reader/books_helper.rb
module Reader::BooksHelper
end

app/helpers/reader/categories_helper.rb
module Reader::CategoriesHelper
end

app/helpers/reader/dashboard_helper.rb
module Reader::DashboardHelper
end

app/helpers/reader/issue_helper.rb
module Reader::IssueHelper
end

app/views/reader/dashboard/index.html.erb
<% if current_user.avatar.attached? %>
<%= image_tag(current_user.avatar, alt: "avatar", class: "avatar",size: "100x100", id: "avatar",class: 'rounded-circle float-right m-3') %>
<% end %>
<div class="jumbotron">

	<h1>Welcome to Reader dashboard</h1>
    
	<%= link_to 'logout', destroy_user_session_path, method: :delete %>
</div>
<div class='container'>
	<div class="btn-group btn-group-lg">
	  <%= link_to 'View Categories',reader_categories_path, class:"btn btn-outline-info" %>
	  <%= link_to 'View Books',reader_books_path, class:"btn btn-outline-success" %>
	  <%= link_to 'View My Issue Requests',reader_issues_path, class:"btn btn-outline-danger" %>
	  <%= link_to 'Create new Issue Request',new_reader_issue_path, class:"btn btn-outline-dark" %>
	</div>
</div>