config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  namespace :reader do
    # root 'dashboard#index'
    resources :books
    resources :categories
    resources :dashboard
    resources :issues 
    get 'issues/return/:id' => "issues#return"

  end
  
  namespace :admin do
    # root 'dashboard#index'
    resources :books
    resources :categories
    resources :dashboard
    resources :issues
    get 'issues/approve/:id' => "issues#approve"
  end

  root 'home#index'

  devise_for :users, controllers: { sessions: 'users/sessions' }
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :category
	extend FriendlyId
  	friendly_id :title, use: :slugged
	
	has_many :issues
	has_many :users,through: :issues

	validates :title, presence: true, length: { minimum: 5 }
	validates :author, presence: true, length: { minimum: 5 }

end

app/models/category.rb
class Category < ApplicationRecord
	has_many :books, dependent: :destroy
	validates :name, presence: true,length: { minimum: 5 }

end

app/models/issue.rb
class Issue < ApplicationRecord
	belongs_to :book
	belongs_to :user

	enum status: %i[notapproved approved returned]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   enum role: %i[reader admin]

   has_many :issues
   has_many :books,through: :users

   has_one_attached :avatar, :dependent => :destroy

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ActionController::Base
	layout 'admin'
	before_action :authenticate_user!
	before_action :check_reader

	private
		def check_reader
			user = current_user
			if user.reader?
				redirect_to reader_dashboard_index_path
			end
		end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::BaseController
  def index
    @books = Book.all
  end

  def show
  end

  def new
    @categories = Category.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
      if @book.save
        redirect_to admin_books_path
      else
        @categories = Category.all
        render :new
      end
  end

  def edit
    @book = Book.friendly.find(params[:id])
    @categories = Category.all
  end

  def update
    @book = Book.friendly.find(params[:id])
    @book.update(book_params)
    if @book.save
      redirect_to admin_books_path
    else
      render :edit
    end
  end

  def destroy
    @book = Book.friendly.find(params[:id])
    if @book.destroy
      redirect_to admin_books_path
    end
  end

  private
    def book_params
      params.require(:book).permit(:title, :author, :category_id)
    end
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < BaseController
    before_action :get_category, only: [:edit, :update, :destroy]
    # before_action :authenticate_user!

    def index
      @categories = Category.all
    end

    def show
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        redirect_to admin_categories_path
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @category.update(category_params)
        redirect_to admin_categories_path
      else  
        render :edit
      end
    end

    def destroy
      if @category.destroy
        redirect_to admin_categories_path
      end
    end

    private

    def get_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
  end
end

app/controllers/admin/issues_controller.rb
class Admin::IssuesController < Admin::BaseController
  def index
  	@issues = Issue.all
  end

  def approve
  	@issue = Issue.find(params[:id])
  	@issue.status = 1
  	if @issue.save
  		redirect_to admin_issues_path
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
before_action :check_roles

	def index; end

	private
		def check_roles
			if(user_signed_in?)	
				user = current_user
				if user.admin?
					redirect_to admin_dashboard_index_path
				elsif user.reader?
					redirect_to reader_dashboard_index_path
				end
			end
		end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/reader/base_controller.rb
class Reader::BaseController < ActionController::Base
	layout 'reader'
	before_action :authenticate_user!
	before_action :check_admin

	private
		def check_admin
			user = current_user
			if user.admin?
				redirect_to admin_dashboard_index_path
			end
		end
end

app/controllers/reader/categories_controller.rb
class Reader::CategoriesController < Reader::BaseController
	def index
		@categories = Category.all
	end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/issue_helper.rb
module Admin::IssueHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_categories_helper.rb
module BookCategoriesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reader/base_helper.rb
module Reader::BaseHelper
end

app/helpers/reader/books_helper.rb
module Reader::BooksHelper
end

app/helpers/reader/categories_helper.rb
module Reader::CategoriesHelper
end

app/helpers/reader/dashboard_helper.rb
module Reader::DashboardHelper
end

app/helpers/reader/issue_helper.rb
module Reader::IssueHelper
end

app/views/admin/categories/_form.html.erb
<div class="container">
<%= form_for [:admin, category] do |form| %>
	
  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name,class:'form-control' %>
  </div>
  <% category.errors.full_messages_for(:name).each do |message| %>
	  <div class="text-danger"><%= message %></div>
	<% end %>
	<br>
  <div>
    <%= form.submit class: 'btn btn-outline-secondary' %>
  </div>
<% end %>
</div>

app/views/admin/categories/create.html.erb
<h1>BookCategories#create</h1>
<p>Find me in app/views/book_categories/create.html.erb</p>

app/views/admin/categories/destroy.html.erb
<h1>BookCategories#destroy</h1>
<p>Find me in app/views/book_categories/destroy.html.erb</p>

app/views/admin/categories/edit.html.erb
<h1 class="jumbotron">Update Category</h1>

<%= render 'form', category:@category %>

app/views/admin/categories/index.html.erb
<div class="jumbotron">
	<h1 class="display-4">Admin Dashboard</h1>
	<p>Welcome to Admin Dashboard</p>
	<%= link_to 'logout', destroy_user_session_path, method: :delete %>
</div>

<div class="container">
	<table class="table table-striped">
		<thead>
			<th>id</th>
			<th>Category Name</th>
			<th>Action</th>
		</thead>
		<tbody>
			<% @categories.each do |cat| %> 
			<tr>
				<td><%= cat.id %></td>
				<td><%= cat.name %></td>
				<td><%= link_to 'Edit',edit_admin_category_path(cat), class: 'btn btn-warning' %>
					<%= link_to 'Delete',admin_category_path(cat), class: 'btn btn-danger', method: :delete ,data: { confirm: "Are you sure?" } %>
				</td>
			</tr>
			<% end%>
		</tbody>
		
	</table>

	<%= link_to 'Add New Category',new_admin_category_path,class:'btn btn-primary' %>
</div>

app/views/admin/categories/new.html.erb
<h1 class="jumbotron">New Category</h1>

<%= render "form",category: @category %>

app/views/admin/categories/show.html.erb
<h1>BookCategories#show</h1>
<p>Find me in app/views/book_categories/show.html.erb</p>